name: fenicsx
channels:
  - defaults
  - conda-forge
dependencies:
  - _openmp_mutex=4.5=3_kmp_llvm
  - aiohappyeyeballs=2.6.1=pyhd8ed1ab_0
  - aiohttp=3.11.16=py313h8060acc_0
  - aiosignal=1.3.2=pyhd8ed1ab_0
  - alsa-lib=1.2.14=hb9d3cd8_0
  - aom=3.9.1=hac33072_0
  - attr=2.5.1=h166bdaf_1
  - attrs=25.3.0=pyh71513ae_0
  - bayesian-optimization=3.1.0=pyhd8ed1ab_0
  - binutils_impl_linux-64=2.43=h4bf12b8_4
  - binutils_linux-64=2.43=h4852527_4
  - blosc=1.21.6=he440d0b_1
  - brotli=1.1.0=hb9d3cd8_2
  - brotli-bin=1.1.0=hb9d3cd8_2
  - brotli-python=1.1.0=py313h46c70d0_2
  - bzip2=1.0.8=h4bc722e_7
  - c-ares=1.34.5=hb9d3cd8_0
  - c-blosc2=2.17.1=h3122c55_0
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - cached-property=1.5.2=py_0
  - cairo=1.18.4=h3394656_0
  - certifi=2025.10.5=pyhd8ed1ab_0
  - cffi=1.17.1=py313hfab6e84_0
  - cftime=1.6.4=py313hf0014fa_0
  - charset-normalizer=3.4.1=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - contourpy=1.3.2=py313h33d0bda_0
  - cpython=3.13.3=py313hd8ed1ab_101
  - cycler=0.12.1=pyhd8ed1ab_1
  - cyrus-sasl=2.1.27=h54b06d7_7
  - dav1d=1.2.1=hd590300_0
  - dbus=1.13.6=h5008d03_3
  - double-conversion=3.3.1=h5888daf_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - expat=2.7.0=h5888daf_0
  - fenics-basix=0.9.0=py313h867a91d_2
  - fenics-basix-nanobind-abi=0.2.1.13=h6c05e69_2
  - fenics-dolfinx=0.9.0=py313hec23ae9_111
  - fenics-ffcx=0.9.0=pyh2e48890_0
  - fenics-libbasix=0.9.0=h7cb7ce6_2
  - fenics-libdolfinx=0.9.0=py313h8d94ac1_111
  - fenics-ufcx=0.9.0=hb7f7608_0
  - fenics-ufl=2024.2.0=pyhd8ed1ab_1
  - ffmpeg=7.1.1=gpl_h0b79d52_704
  - fftw=3.3.10=mpi_openmpi_h99e62ba_10
  - fltk=1.3.10=hff38c0f_0
  - fmt=11.1.4=h07f6e7f_1
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.57.0=py313h8060acc_0
  - freeglut=3.4.0=h8b03031_1
  - freeimage=3.18.0=h3a85593_22
  - freetype=2.13.3=h48d6fc4_0
  - fribidi=1.0.10=h36c2ea0_0
  - frozenlist=1.5.0=py313h8060acc_1
  - gcc_impl_linux-64=13.3.0=h1e990d8_2
  - gcc_linux-64=13.3.0=hc28eda2_9
  - gdk-pixbuf=2.42.12=hb9ae30d_0
  - gettext=0.23.1=h5888daf_0
  - gettext-tools=0.23.1=h5888daf_0
  - gl2ps=1.4.2=hae5d5c5_1
  - glew=2.1.0=h9c3ff4c_2
  - gmp=6.3.0=hac33072_2
  - gmpy2=2.1.5=py313h11186cd_3
  - gmsh=4.13.1=hccb25f3_1
  - graphite2=1.3.13=h59595ed_1003
  - h2=4.2.0=pyhd8ed1ab_0
  - h5py=3.13.0=nompi_py313hff19e9a_100
  - harfbuzz=11.1.0=h3beb420_0
  - hdf4=4.2.15=h2a13503_7
  - hdf5=1.14.3=mpi_openmpi_h39ae36c_9
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - hypre=2.32.0=mpi_openmpi_h398ea61_1
  - icu=75.1=he02047a_0
  - idna=3.10=pyhd8ed1ab_1
  - imath=3.1.12=h7955e40_0
  - importlib-metadata=8.6.1=pyha770c72_0
  - importlib_metadata=8.6.1=hd8ed1ab_0
  - iniconfig=2.0.0=pyhd8ed1ab_1
  - jack=1.9.22=h7c63dc7_2
  - jasper=4.2.5=h1920b20_0
  - jax=0.6.0=pyhd8ed1ab_0
  - jaxlib=0.6.0=cpu_py313h8f0a827_0
  - joblib=1.4.2=py313h06a4308_0
  - jsoncpp=1.9.6=hf42df4d_1
  - jxrlib=1.1=h7b6447c_2
  - kahip=3.18=h4664ef3_0
  - kernel-headers_linux-64=3.10.0=he073ed8_18
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.7=py313h33d0bda_0
  - krb5=1.21.3=h659f571_0
  - lame=3.100=h166bdaf_1003
  - lcms2=2.17=h717163a_0
  - ld_impl_linux-64=2.43=h712a8e2_4
  - lerc=4.0.0=h27087fc_0
  - level-zero=1.21.9=h84d6215_0
  - libabseil=20250127.1=cxx17_hbbce691_0
  - libadios2=2.10.2=mpi_openmpi_h9d748f7_5
  - libaec=1.1.3=h59595ed_0
  - libamd=3.3.3=h456b2da_7100101
  - libasprintf=0.23.1=h8e693c7_0
  - libasprintf-devel=0.23.1=h8e693c7_0
  - libass=0.17.3=h52826cd_2
  - libblas=3.9.0=31_h59b9bed_openblas
  - libboost=1.86.0=h6c02f8c_3
  - libboost-devel=1.86.0=h1a2810e_3
  - libboost-headers=1.86.0=ha770c72_3
  - libbrotlicommon=1.1.0=hb9d3cd8_2
  - libbrotlidec=1.1.0=hb9d3cd8_2
  - libbrotlienc=1.1.0=hb9d3cd8_2
  - libbtf=2.3.2=hf02c80a_7100101
  - libcamd=3.3.3=hf02c80a_7100101
  - libcap=2.75=h39aace5_0
  - libcblas=3.9.0=31_he106b2a_openblas
  - libccolamd=3.3.4=hf02c80a_7100101
  - libcholmod=5.3.1=h9cf07ce_7100101
  - libclang-cpp20.1=20.1.3=default_h1df26ce_0
  - libclang13=20.1.3=default_he06ed0a_0
  - libcolamd=3.3.4=hf02c80a_7100101
  - libcups=2.3.3=h4637d8d_4
  - libcurl=8.13.0=h332b0f4_0
  - libdb=6.2.32=h9c3ff4c_0
  - libdeflate=1.23=h4ddbbb0_0
  - libdrm=2.4.124=hb9d3cd8_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libegl=1.7.0=ha4b6fd6_2
  - libev=4.33=hd590300_2
  - libevent=2.1.12=hf998b51_1
  - libexpat=2.7.0=h5888daf_0
  - libfabric=2.1.0=ha770c72_0
  - libfabric1=2.1.0=h14e6f36_0
  - libffi=3.4.6=h2dba641_1
  - libflac=1.4.3=h59595ed_0
  - libgcc=14.2.0=h767d61c_2
  - libgcc-devel_linux-64=13.3.0=hc03c837_102
  - libgcc-ng=14.2.0=h69a702a_2
  - libgcrypt-lib=1.11.0=hb9d3cd8_2
  - libgettextpo=0.23.1=h5888daf_0
  - libgettextpo-devel=0.23.1=h5888daf_0
  - libgfortran=14.2.0=h69a702a_2
  - libgfortran-ng=14.2.0=h69a702a_2
  - libgfortran5=14.2.0=hf1ad2bd_2
  - libgl=1.7.0=ha4b6fd6_2
  - libglib=2.84.1=h2ff4ddf_0
  - libglu=9.0.3=h03adeef_0
  - libglvnd=1.7.0=ha4b6fd6_2
  - libglx=1.7.0=ha4b6fd6_2
  - libgomp=14.2.0=h767d61c_2
  - libgpg-error=1.53=hbd13f7d_0
  - libgrpc=1.71.0=h8e591d7_1
  - libhwloc=2.11.2=default_h0d58e46_1001
  - libiconv=1.18=h4ce23a2_1
  - libjpeg-turbo=3.0.0=hd590300_1
  - libklu=2.3.5=h95ff59c_7100101
  - liblapack=3.9.0=31_h7ac8fdf_openblas
  - libllvm20=20.1.3=he9d0ab4_0
  - liblzma=5.8.1=hb9d3cd8_0
  - libmpdec=4.0.0=h4bc722e_0
  - libnetcdf=4.9.2=nompi_h00e09a9_116
  - libnghttp2=1.64.0=h161d5f1_0
  - libnl=3.11.0=hb9d3cd8_0
  - libntlm=1.8=hb9d3cd8_0
  - libogg=1.3.5=h4ab18f5_0
  - libopenblas=0.3.29=openmp_hd680484_0
  - libopenvino=2025.0.0=hdc3f47d_3
  - libopenvino-auto-batch-plugin=2025.0.0=h4d9b6c2_3
  - libopenvino-auto-plugin=2025.0.0=h4d9b6c2_3
  - libopenvino-hetero-plugin=2025.0.0=h981d57b_3
  - libopenvino-intel-cpu-plugin=2025.0.0=hdc3f47d_3
  - libopenvino-intel-gpu-plugin=2025.0.0=hdc3f47d_3
  - libopenvino-intel-npu-plugin=2025.0.0=hdc3f47d_3
  - libopenvino-ir-frontend=2025.0.0=h981d57b_3
  - libopenvino-onnx-frontend=2025.0.0=h0e684df_3
  - libopenvino-paddle-frontend=2025.0.0=h0e684df_3
  - libopenvino-pytorch-frontend=2025.0.0=h5888daf_3
  - libopenvino-tensorflow-frontend=2025.0.0=h684f15b_3
  - libopenvino-tensorflow-lite-frontend=2025.0.0=h5888daf_3
  - libopus=1.5.2=hd0c01bc_0
  - libpciaccess=0.18=hd590300_0
  - libpmix=5.0.7=h658e747_0
  - libpng=1.6.47=h943b412_0
  - libpq=17.4=h27ae623_1
  - libprotobuf=5.29.3=h501fc15_0
  - libptscotch=7.0.6=h7e1c861_1
  - libraw=0.21.4=h9969a89_0
  - libre2-11=2024.07.02=hba17884_3
  - librsvg=2.58.4=he92a37e_3
  - libsanitizer=13.3.0=he8ea267_2
  - libscotch=7.0.6=hd4c538f_1
  - libsndfile=1.2.2=hc60ed4a_1
  - libsodium=1.0.20=h4ab18f5_0
  - libspqr=4.3.4=h23b7119_7100101
  - libsqlite=3.49.1=hee588c1_2
  - libssh2=1.11.1=hf672d98_0
  - libstdcxx=14.2.0=h8f9b012_2
  - libstdcxx-ng=14.2.0=h4852527_2
  - libsuitesparseconfig=7.10.1=h901830b_7100101
  - libsystemd0=257.4=h4e0b6ca_1
  - libtheora=1.1.1=h4ab18f5_1006
  - libtiff=4.7.0=hd9ff511_3
  - libudev1=257.4=hbe16f8c_1
  - libumfpack=6.3.5=h873dde6_7100101
  - libunwind=1.6.2=h9c3ff4c_0
  - liburing=2.9=h84d6215_0
  - libusb=1.0.28=hb9d3cd8_0
  - libuuid=2.38.1=h0b41bf4_0
  - libva=2.22.0=h4f16b4b_2
  - libvorbis=1.3.7=h9c3ff4c_0
  - libvpx=1.14.1=hac33072_0
  - libwebp-base=1.5.0=h851e524_0
  - libxcb=1.17.0=h8a09558_0
  - libxkbcommon=1.8.1=hc4a0caf_0
  - libxml2=2.13.7=h4bc477f_1
  - libzip=1.11.2=h6991a6a_0
  - libzlib=1.3.1=hb9d3cd8_2
  - llvm-openmp=20.1.3=h024ca30_0
  - loguru=0.7.2=py313h78bf25f_2
  - lz4-c=1.10.0=h5888daf_1
  - markdown-it-py=2.2.0=py313h06a4308_1
  - matplotlib-base=3.10.1=py313h129903b_0
  - mdurl=0.1.0=py313h06a4308_0
  - meshio=5.3.5=pyhd8ed1ab_0
  - metis=5.1.0=hd0bcaf9_1007
  - ml_dtypes=0.5.1=py313ha87cce1_0
  - mpc=1.3.1=h24ddda3_1
  - mpfr=4.2.1=h90cbb55_3
  - mpg123=1.32.9=hc50e24c_0
  - mpi=1.0=openmpi
  - mpi4py=4.0.3=py313hffb1895_0
  - mpmath=1.3.0=pyhd8ed1ab_1
  - msgpack-python=1.1.0=py313h33d0bda_0
  - multidict=6.3.2=py313h8060acc_0
  - mumps-include=5.7.3=hd53efc5_9
  - mumps-mpi=5.7.3=hffc5ed9_9
  - munkres=1.1.4=pyh9f0ad1d_0
  - mysql-common=9.2.0=h266115a_0
  - mysql-libs=9.2.0=he0572af_0
  - ncurses=6.5=h2d0b736_3
  - netcdf4=1.7.2=nompi_py313h2a70696_101
  - nlohmann_json=3.12.0=h3f2d84a_0
  - numpy=2.2.4=py313h17eae1a_0
  - occt=7.8.1=all_h4c4714a_203
  - ocl-icd=2.3.3=hb9d3cd8_0
  - opencl-headers=2024.10.24=h5888daf_0
  - openexr=3.3.3=hff63da0_0
  - openh264=2.6.0=hc22cd8d_0
  - openjpeg=2.5.3=h5fbd93e_0
  - openldap=2.6.9=he970967_0
  - openmpi=5.0.7=hb85ec53_100
  - openssl=3.5.4=h26f9b46_0
  - opt_einsum=3.4.0=pyhd8ed1ab_1
  - packaging=24.2=pyhd8ed1ab_2
  - pandas=2.3.1=py313h08cd8bf_0
  - pango=1.56.3=h9ac818e_1
  - parmetis=4.0.3=h02de7a9_1007
  - patsy=1.0.1=pyhd8ed1ab_1
  - pcre2=10.44=hba22ea6_2
  - petsc=3.22.3=real_h883bb10_103
  - petsc4py=3.22.4=np2py313hb53d446_0
  - pillow=11.1.0=py313h8db990d_0
  - pip=25.0.1=pyh145f28c_0
  - pixman=0.44.2=h29eaf8c_0
  - pkg-config=0.29.2=h4bc722e_1009
  - platformdirs=4.3.7=pyh29332c3_0
  - pluggy=1.6.0=pyhd8ed1ab_0
  - pooch=1.8.2=pyhd8ed1ab_1
  - proj=9.5.1=h0054346_0
  - propcache=0.3.1=py313h8060acc_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - pugixml=1.15=h3f63f65_0
  - pulseaudio-client=17.0=hac146a9_1
  - pycparser=2.22=pyh29332c3_1
  - pygments=2.19.1=py313h06a4308_0
  - pyparsing=3.2.3=pyhd8ed1ab_1
  - pysocks=1.7.1=pyha55dd90_7
  - pytest=8.4.2=pyhd8ed1ab_0
  - python=3.13.3=hf636f53_101_cp313
  - python-dateutil=2.9.0.post0=pyhff2d567_1
  - python-gmsh=4.13.1=h57928b3_1
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - python_abi=3.13=6_cp313
  - pytz=2024.1=py313h06a4308_0
  - pyvista=0.44.2=pyhd8ed1ab_1
  - qhull=2020.2=h434a139_5
  - qt6-main=6.8.3=h6441bc3_2
  - rapidjson=1.1.0=hdb19cb5_1
  - rdma-core=56.1=h5888daf_1
  - re2=2024.07.02=h9925aae_3
  - readline=8.2=h8c095d6_2
  - requests=2.32.3=pyhd8ed1ab_1
  - rich=13.9.4=py313h06a4308_0
  - scalapack=2.2.0=h16fb9de_4
  - scikit-learn=1.7.0=py313h8ef605b_1
  - scipy=1.15.2=py313h86fcf2b_0
  - scooby=0.10.0=pyhd8ed1ab_1
  - sdl2=2.32.54=h9b8e6db_0
  - sdl3=3.2.10=h3083f51_0
  - seaborn=0.13.2=hd8ed1ab_3
  - seaborn-base=0.13.2=pyhd8ed1ab_3
  - setuptools=78.1.0=pyhff2d567_0
  - six=1.17.0=pyhd8ed1ab_0
  - slepc=3.22.2=real_h221cefa_300
  - slepc4py=3.22.2=py313h004cd3b_0
  - snappy=1.2.1=h8bd8927_1
  - spdlog=1.15.2=h10b92b3_0
  - sqlite=3.49.1=h9eae976_2
  - statsmodels=0.14.4=py313ha014f3b_1
  - superlu=7.0.0=h832b8c9_1
  - superlu_dist=9.1.0=h3349319_0
  - svt-av1=3.0.2=h5888daf_0
  - sympy=1.13.3=pyh2585a3b_105
  - sysroot_linux-64=2.17=h0157908_18
  - tbb=2022.1.0=h4ce085d_0
  - threadpoolctl=3.5.0=py313h7040dfc_0
  - tk=8.6.13=noxft_h4845f30_101
  - tomli=2.2.1=pyhe01879c_2
  - typing-extensions=4.13.2=h0e9735f_0
  - typing_extensions=4.13.2=pyh29332c3_0
  - tzdata=2025b=h78e105d_0
  - ucc=1.3.0=had72a48_5
  - ucx=1.18.0=hfd9a62f_3
  - urllib3=2.4.0=pyhd8ed1ab_0
  - utfcpp=4.0.6=h005c6e1_0
  - vtk=9.3.1=qt_py313h71fb23e_216
  - vtk-base=9.3.1=qt_py313ha954bcc_216
  - vtk-io-ffmpeg=9.3.1=qt_py313h71fb23e_216
  - wayland=1.23.1=h3e06ad9_0
  - wayland-protocols=1.43=hd8ed1ab_0
  - wslink=2.3.3=pyhd8ed1ab_0
  - x264=1!164.3095=h166bdaf_2
  - x265=3.5=h924138e_3
  - xcb-util=0.4.1=hb711507_2
  - xcb-util-cursor=0.1.5=hb9d3cd8_0
  - xcb-util-image=0.4.0=hb711507_2
  - xcb-util-keysyms=0.4.1=hb711507_0
  - xcb-util-renderutil=0.3.10=hb711507_0
  - xcb-util-wm=0.4.2=hb711507_0
  - xkeyboard-config=2.43=hb9d3cd8_0
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.12=h4f16b4b_0
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxcomposite=0.4.6=hb9d3cd8_2
  - xorg-libxcursor=1.2.3=hb9d3cd8_0
  - xorg-libxdamage=1.1.6=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxfixes=6.0.1=hb9d3cd8_0
  - xorg-libxi=1.8.2=hb9d3cd8_0
  - xorg-libxmu=1.2.1=h9b100fa_1
  - xorg-libxrandr=1.5.4=hb9d3cd8_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xorg-libxscrnsaver=1.2.4=hb9d3cd8_0
  - xorg-libxt=1.3.1=hb9d3cd8_0
  - xorg-libxtst=1.2.5=hb9d3cd8_3
  - xorg-libxxf86vm=1.1.6=hb9d3cd8_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - yaml=0.2.5=h7f98852_2
  - yarl=1.18.3=py313h8060acc_1
  - zeromq=4.3.5=h3b0a872_7
  - zfp=1.0.1=h5888daf_2
  - zipp=3.21.0=pyhd8ed1ab_1
  - zlib=1.3.1=hb9d3cd8_2
  - zlib-ng=2.2.4=h7955e40_0
  - zstandard=0.23.0=py313h536fd9c_1
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
      - myproject==0.1.0
      - npeet==1.0.1
prefix: /projectnb/lejlab2/pprachas/.conda/envs/fenicsx
